### ISSUE TITLE
new threads and drafts route

### ISSUE THREAD

**Issue by Diivvuu** [Diivvuu/slack-clone-nextjs#4]
**Is your feature request related to a problem? Please describe.**
whenever we click here on threads or drafts and sent, need to add a new route to reflect all the threads/ or make it unclickable

**Describe alternatives you've considered**
![image](https://github.com/user-attachments/assets/4067baeb-3d93-4674-9b0a-51c96beb5e02)

**Comment by Code1Crusader** [comment]
Just want to confirm, when 'Threads' is clicked it should display a dropdown of all the threads in a menu below or it should be made unclickable?

**Comment by Diivvuu** [comment]
on click of drafts you can just highlight the drafts that are present in current workspace's quill ref if there is no draft than nothing but a toaster of "no drafts in current workspace"
for threads you can use the drop down to highlight the name and count of replies to parent message of every message with a conversationId to it (use this in backend "by_channel_id_by_conversation_id] )
